Description: Conda
Engine: gotpl
Home: http://kuberlab.com
Icon: https://conda.io/docs/_images/conda_logo.svg
Keywords:
- conda
- template
- kuberlab
- kuberlabapptemplate
Maintainers:
- Email: agunin@kuberlab.com
  Name: Gunin Alexander
Name: conda
Version: 1.0.0
Type: mlapp-v2
