storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

env:
  value: "kuberlab"
  wizard:
    name: "Conda environment"
    kind: select
    dynamic: true
    options:
    - "kuberlab"

global_env:
  value: true
  wizard:
    name: "Use global environment"
    kind: boolean

jupyter:
  value: true
  wizard:
    name: Install Jupyter
    kind: boolean

jupyter_contrib_nbextensions:
  value: false
  wizard:
    name: Install Jupyter Extensions
    kind: boolean

src:
  value: https://github.com/kuberlab/tensorflow-examples
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset configuration"
   kind: dataset